import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from 'react-hot-toast'
import 'bootstrap-icons/font/bootstrap-icons.css'
const inter = Inter({ subsets: ["latin"] });
import { cookies } from "next/headers";
import NextTopLoader from 'nextjs-toploader';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
async function logout(){
  'use server'
  const cookie=cookies().delete('token');
  return {
    status:'success',

  }
}
export default function RootLayout({ children }) {
  const cookie=cookies().get('token');
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader color="#E60000" height={2} speed={200}   showSpinner={false} />
        <Toaster />
        <Navbar logout={logout} auths={cookie} />
        {children}</body>
    </html>
  );
}
